//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboGestionProgrammeBdFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDPlanCadreDEVEntities : DbContext
    {
        public BDPlanCadreDEVEntities()
            : base("name=BDPlanCadreDEVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<tblCodeProgramme> tblCodeProgramme { get; set; }
        public virtual DbSet<tblContexteRealisation> tblContexteRealisation { get; set; }
        public virtual DbSet<tblCriterePerformance> tblCriterePerformance { get; set; }
        public virtual DbSet<tblElementCompetence> tblElementCompetence { get; set; }
        public virtual DbSet<tblEnonceCompetence> tblEnonceCompetence { get; set; }
        public virtual DbSet<tblProgramme> tblProgramme { get; set; }
        public virtual DbSet<tt> tt { get; set; }
    }
}
