//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboGestionProgrammeBdFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCodeProgramme
    {
        public int id { get; set; }
        public string code { get; set; }
        public string commentaire { get; set; }
    
        public virtual tblProgramme tblProgramme { get; set; }
    }
}
