//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboGestionProgrammeBdFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContexteRealisation
    {
        public int idContexte { get; set; }
        public string contexteRealisation { get; set; }
        public string commentaire { get; set; }
        public int idCompetence { get; set; }
    
        public virtual tblEnonceCompetence tblEnonceCompetence { get; set; }
    }
}
