//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboGestionProgrammeBdFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCriterePerformance
    {
        public int idCritere { get; set; }
        public string criterePerformance { get; set; }
        public int numero { get; set; }
        public string commentaire { get; set; }
        public int idElement { get; set; }
    
        public virtual tblElementCompetence tblElementCompetence { get; set; }
    }
}
