//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboGestionProgrammeBdFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEnonceCompetence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEnonceCompetence()
        {
            this.tblContexteRealisation = new HashSet<tblContexteRealisation>();
            this.tblElementCompetence = new HashSet<tblElementCompetence>();
        }
    
        public int idCompetence { get; set; }
        public string codeCompetence { get; set; }
        public string enonceCompetence { get; set; }
        public string motClef { get; set; }
        public bool obligatoire { get; set; }
        public bool actif { get; set; }
        public string commentaire { get; set; }
        public int idProgramme { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblContexteRealisation> tblContexteRealisation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblElementCompetence> tblElementCompetence { get; set; }
        public virtual tblProgramme tblProgramme { get; set; }
    }
}
